alias rg="grep --exclude=\*.svn\* -Rn"
alias ack="ack-grep"
alias tm="tmux"
alias tmdev="tmux attach -t dev"
alias tmbro="tmux attach -t brochure"
alias rmsvn="find . -name .svn -exec rm -rf {} \;"
alias nyan="telnet miku.acm.uiuc.edu"

alias fixfuse="fusermount -zu ~/.gvfs;/usr/lib/gvfs/gvfs-fuse-daemon ~/.gvfs"
alias mysqlsock="ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock"

# Git shortcuts
alias gst="git status"
alias gd="git diff"
alias gcm="git commit -a -m"
alias gco="git checkout"
alias gbr="git branch"
alias gbd="git branch -D"

alias rake="bundle exec rake"

# ShuntYard
alias prj="cd ~/projects"
alias eltar="tar --strip-components=2 -zxvf "
