alias rg="grep --exclude=\*.svn\* -Rn"
alias ack="ack-grep"
alias tm="tmux"
alias tmdev="tmux attach -t dev"
alias tmbro="tmux attach -t brochure"
alias rmsvn="find . -name .svn -exec rm -rf {} \;"
alias nyan="telnet miku.acm.uiuc.edu"

alias fixfuse="fusermount -zu ~/.gvfs;/usr/lib/gvfs/gvfs-fuse-daemon ~/.gvfs"
alias mysqlsock="ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock"

# Git shortcuts
alias gst="git status"
alias gcb="git checkout -b "
alias gco="git checkout "
alias gcm="git commit -m "
alias gdf="git diff "
alias gbr="git branch -a"

# ShuntYard
alias prj="cd ~/projects"
